<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kusuma Hastuti Jaya Wardani">
<meta name="dcterms.date" content="2024-01-24">

<title>Analisis Regresi Pengaruh Luas Lahan Perkebunan Tebu Terhadap Produksi Gula Tebu Pada Periode 2012-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Regresi Pengaruh Luas Lahan Perkebunan Tebu Terhadap Produksi Gula Tebu Pada Periode 2012-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kusuma Hastuti Jaya Wardani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp%20(1).jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Beberapa wilayah di Indonesia mengandalkan roda perekonomiannya pada sektor hasil perkebunan dan pertanian, salah satunya adalah hasil perkebunan tebu. Tanaman tebu dapat menghasilkan berbagai macam produk yang memiliki nilai jual tinggi, contohnya gula tebu. Itu artinya industri produksi gula tebu menjadi salah satu aspek perekonomian serta berkontribusi terhadap ketahanan pangan serta kesejahteraan masyarakat. Oleh karena itu, penting untuk memahami faktor-faktor apa saja yang dapat mempengaruhi tingkat produksi gula tebu untuk memastikan keberlanjutan dan peningkatan produktivitas di sektor ini. Salah satu faktor yang dapat mempengaruhi produksi gula tebu adalah luas areal perkebunan tebu itu sendiri. Luas perkebunan tebu di suatu wilayah dapat berdampak signifikan terhadap produksi gula tebu. Hal ini menunjukkan bahwa Paper dengan judul “Analisis Regresi Pengaruh Luas Lahan Perkebunan Tebu terhadap Produksi Gula Tebu pada Periode 2012-2022” menjadi salah satu kajian yang relevan dan bermanfaat. Penulisan serta penelitian ini bertujuan untuk memberikan pemahaman yang lebih mendalam terkait hubungan antara luas lahan perkebunan dan produksi gula tebu.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penulisan paper penelitian ini mengkaji pengaruh luas lahan perkebunan tebu terhadap produksi gula tebu di Indonesia. Penelitian ini menggunakan data adari Badan Pusat Statistik (BPS). Ruang lingkup penelitian ini melibatkan 1 variable independent yaitu Luas Lahan Perkebunan Tebu. Adapun data yang dipakai adalah data yang sifatnya time series yaitu dalam periode 2012-2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Seperti apa hubungan antara luas lahan perkebunan tebu dengan produksi gula tebu selama periode 2012-2022</li>
<li>Bagaimana Luas lahan perkebunan tebu bisa mempengaruhi produksi gula tebu?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>penelitian ini bertujuan untuk menganalisis hubungan antara luas lahan perkebunan tebu dengan produksi gula tebu serta mengetahui alasan mengapa luas lahan perkebunan dapat mempengaruhi produksi gula tebu. Selain itu, penelitian ini diharapkan dapat memberikan informasi yang lebih mendalam tentang salah satu faktor produksi gula tebu yaitu luas lahan perkebunan</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<section id="perkebunan-tebu-di-indonesia." class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="perkebunan-tebu-di-indonesia."><span class="header-section-number">2.1</span> Perkebunan tebu Di Indonesia.</h3>
<p>Tebu sudah menjadi tanaman budidaya di Indonesia sebelum zaman Kolonial belanda&nbsp;(Evizal, 2018). Tanaman tebu juga menjadi salah satu tanaman yang tanam paksa di nusantara di tahun 1830-1870. Sehingga memang dari dulu gula tebu asal Indonesia sudah diminati di kalangan internasional. Indoenesia pernah mengalami kejayaan dalam ekspor gula (Yusuf, Aulia, &amp; Martadi, 2010). Namun jika dilihat dari data di situs trade map, indoneisa lebhih banyak mengimpor gula dari pada mengekspor gula tebu</p>
</section>
<section id="tebu" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="tebu"><span class="header-section-number">2.2</span> Tebu</h3>
<p>Tanaman tebu yang memiliki nama latin <em>Saccharum Officinarum L.</em> menajdi salah satu tanaman budidaya perkebunan di indoensia yang memiliki nilai ekonomi yang tinggi (Anwar, Redjeki, &amp; Budi, 2021). &nbsp;Tanaman tebu menjadi bahan baku utama dalam industry gula. Sementara itu, gula merupakan kebutuhan pokok bagi masyarakat indoensia (Anggraini &amp; Hartatie, 2023) yang konsumsinya selalu meningkat dari tahun ketahun. Oleh karena itu petani tebu menjadi salah satu mata pencaharian masyarakat didaerah Indonesia khususnya daerah penghasil tebu seperti provinsi Jawa timus, lampung, jawa tengah, sumatera selatan, dan sebagainya (Direktorat Statistik Tanaman Pangan, 2022)</p>
</section>
<section id="produksi-gula-tebu" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="produksi-gula-tebu"><span class="header-section-number">2.3</span> Produksi Gula Tebu</h3>
<p>Kualitas gula tebu ditentukan oleh kandungan nira yang terdapat dalam tebu. Rendahnya nira tebu dapat mempengaruhi hasil produksi tinggi (Anwar, Redjeki, &amp; Budi, 2021). Pada tahun 2017, produktivitas gula tebu lebih rendah dari pada negara pengahsil tebu lainnya seperti brazil, dan india. Selain dipengaruhi oleh kandungan nira, kualitas tebu juga dipengaruhi oleh beberapa hal misalnya suhu dan luas lahan perkebunan tebu. Menurut WTO (<em>World Trade Organization),</em> gula menjadi salah satu komoditas khusus sebagai salah satu upaya mewujudkan ketahanan pangan di Indonesia&nbsp;(Pramudya &amp; Pamungkas, 2022)</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Penelitian ini menggunakan data luas lahan perkebunan tebu dan produksi gula tebu di indonesia dari tahun 2012-2022, datanya sebagai berikut:</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Luas Lahan Perkebunan Tebu (Ha)</th>
<th>Produksi Gula Tebu (Ton)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>442658</td>
<td>2592561</td>
</tr>
<tr class="even">
<td>2013</td>
<td>470941</td>
<td>2553551</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>472676</td>
<td>2575392</td>
</tr>
<tr class="even">
<td>2015</td>
<td>455819</td>
<td>2534872</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>447350</td>
<td>2363042</td>
</tr>
<tr class="even">
<td>2017</td>
<td>420146</td>
<td>2190979</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>415663</td>
<td>2171726</td>
</tr>
<tr class="even">
<td>2019</td>
<td>413054</td>
<td>2227051</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>418996</td>
<td>2123405</td>
</tr>
<tr class="even">
<td>2021</td>
<td>449008</td>
<td>2348331</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>490008</td>
<td>2402648</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/kusuma_hastuti"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data_metopel <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data_metopel.xlsx"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data_metopel)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data =</span> data_metopel)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>data_metopel<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_metopel<span class="sc">$</span>X,data_metopel<span class="sc">$</span>u,<span class="at">xlab =</span> <span class="st">"Luas lahan perkebunan tebu"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Luas Lahan Perkebunan Tebu</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_metopel <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data_metopel.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data_metopel)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data =</span> data_metopel)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>data_metopel<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_metopel<span class="sc">$</span>Y,data_metopel<span class="sc">$</span>u,<span class="at">xlab =</span> <span class="st">"Produksi Gula Tebu"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Produksi gula tebu.</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis yang dipilih untuk penelitian ini adalah regresi univariat yaitu model regresi yang terdiri dari satu variabel dependent yaitu Produksi gula tebu, dan satu variable independent yaitu luas lahan perkebunan tebu.</p>
<p>Penelitian ini bermaksud untuk mengkaji hubungan antara luas lahan perkebunan tebu (X) dengan produksi gula tebu (Y)</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span></p>
<p>Dimana <span class="math inline">\(y_t\)</span> adalah Y dan <span class="math inline">\(x_t\)</span> dalah X.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t-value</th>
<th>Prob(.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>intercept</td>
<td><pre><code>1.194e+05</code></pre></td>
<td><pre><code>6.584e+05</code></pre></td>
<td><pre><code>0.181</code></pre></td>
<td><pre><code>0.86010</code></pre></td>
</tr>
<tr class="even">
<td>X</td>
<td><pre><code>5.059e+00</code></pre></td>
<td><pre><code>1.477e+00</code></pre></td>
<td><pre><code>3.426</code></pre></td>
<td><pre><code> 0.00756</code></pre></td>
</tr>
<tr class="odd">
<td>R squared</td>
<td>0.566</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-Squared</td>
<td>0.5177</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-Statistic</td>
<td>11.73</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob (F-Statistic)</td>
<td>0.00756</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Dari tabel diatas, maka jika dimaksukkan ke persamaan regresi akan menjadi seperti ini</p>
<p><strong><em>Y = 1.194 + 5.059X</em></strong></p>
<p>Luas Lahan perkebunan tebu memiliki hubungan positif dengan produksi gula tebu. Maka, setiap kenaikan luas lahan perkebunan tebu yang diandaikan sebesar 1% maka jumlah produksi gula tenu meningkat sebesar 5,059%. Namun, produksi gula tebu akan menurun 1.194% jika luas perkebunan tebu = 0</p>
<p>Besarnya koefisien R Squared yaitu 0.566 menggambarkan bahwa sebesar 56.6% variabel dependen dapat dijelaskan oleh model regresi. Sementara koefisien F-Statistic yang tinggi dan koefisien p-value yang kecil menggambarkan bahwa model secara keseluruhan memiliki kecenderungan yang signifikan. Oleh karena itu, dapat disimpulkan bahwa Luas lahan perkebunan tebu berpengaruh terhdap produksi gula tebu di indonesia</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data =</span> data_metopel)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = data_metopel)

Residuals:
    Min      1Q  Median      3Q     Max 
-195670  -52199  -19472   58223  233783 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 1.194e+05  6.584e+05   0.181  0.86010   
X           5.059e+00  1.477e+00   3.426  0.00756 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 121600 on 9 degrees of freedom
Multiple R-squared:  0.566, Adjusted R-squared:  0.5177 
F-statistic: 11.73 on 1 and 9 DF,  p-value: 0.00756</code></pre>
</div>
</div>
<p>Dari hasil regresi diatas, maka setiap kenaikan luas lahan perkebunan tebu yang diandaikan sebesar 1% maka jumlah produksi gula tenu meningkat sebesar 5,059%. Namun, produksi gula tebu akan menurun 1.194% jika luas perkebunan tebu = 0</p>
<pre><code></code></pre>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Didasarkan pada penetian yang sudah dilakukan, maka dapat disimpulkan bahwa luas lahan perkebunan tebu berpengaruh terhadap produksi gula tebu. hal ini dikarenakan dengan adanya perluasan lahan perkebunan akan memperbanyak jumlah tanaman tebu yang di tanam yang nantinya akan dipanen dan menjadi bahan baku utama gula tebu.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Anggraini, R., &amp; Hartatie, D. (2023). Pengaruh Asal Bahan Tanam dan Macam Varietas tebu (Saccarum officinarum. L) terhadap Pertumbuhan Vegetatif Bibit pada Portray . <em>Agropross National Conference Procceedings of Agriculture</em> , 2-2.</p>
<p>Anwar, K., Redjeki, E. S., &amp; Budi, S. (2021). Perbedaan Pertumbuhan dan Hasil Tiga Klon Tanaman Tebu (Saccharum officinarum L.) Pada Tanah Aluvial di Didesa Sambiroto Kecamatan Sooko-Mojokerto. <em>Jurnal Tropocrops</em>, 2-2.</p>
<p>Direktorat Statistik Tanaman Pangan, H. d.&nbsp;(2022). <em>Statistik Tebu Indoneisa 2022.</em> BPS RI/BPS - Statistics Indonesia.</p>
<p>Evizal, R. (2018). <em>Pengelolaan Perkebunan Tebu.</em> Yogyakarta: GRAHA ILMU.</p>
<p>Pramudya, Y., &amp; Pamungkas, S. S. (2022). Studi Respon Cekaman Garam Terhadap Kondisi Tanaman Tebu (Saccharum Officinarum). <em>Open Science and Technology</em>, 2-3.</p>
<p>Yusuf, Y., Aulia, A. F., &amp; Martadi, S. (2010). Permintaan Gula Pasit di Indonesia. <em>Jurnal Ekonomi</em>, 1-1.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>